### ISSUE TITLE
[bug] Complex object component images (full image for zoom/pan) doesn't display in MS Chrome and Edge - Calisphere prod and stage

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#871] opened 2024-04-16 19:35 UTC
This looks like a new front-end issue, on -stage and in prod, with MS Chrome and Edge browsers -- appears to be isolated to viewing Nuxeo complex object components: the full zoom/pan view of images is not displaying (in addition to the thumbnail images in the carousel, as noted in https://github.com/orgs/ucldc/projects/1/views/16?pane=issue&itemId=59833306) 

https://calisphere.org/item/ark:/86086/n24t6jh3/ 
https://calisphere.org/item/ark:/86086/n21n836s/?order=1 

https://calisphere-stage.cdlib.org/item/ark:/86086/n21n836s/?order=0
https://calisphere-stage.cdlib.org/item/ark:/86086/n21n836s/?order=1 

We checked this when QA'ing -test and -prod over the past week, and everything appeared to be fine.

(Reported in Freshdesk: https://help.oac.cdlib.org/a/tickets/137091)

**Comment by amywieliczka** [comment] 2024-04-16 20:20
This is an http vs. https iiif server issue and should be resolved with @barbarahui's new cloudfront distro? 
calisphere-stage is currently down, though.

**Comment by barbarahui** [comment] 2024-04-16 20:55
Everything looks fine to me on calisphere-stage.

I do see the issue on calisphere production. Was this previously resolved on prod?

**Comment by amywieliczka** [comment] 2024-04-16 20:56
@barbarahui this was never resolved on prod. Chrome is just being pickier about mixed content.

**Comment by amywieliczka** [comment] 2024-04-16 20:57
But maybe there's another issue too, if Adrian is seeing problems on calisphere-stage?

**Comment by barbarahui** [comment] 2024-04-16 21:01
Oh hrm, I take that back. I do see an issue on calisphere-stage but the errors seem unrelated to the http vs https issue. In the browser console I see an error related to vendor.js:

```
Uncaught TypeError: Cannot read properties of null (reading 'add')
    at s.initADA (vendor.js:1:148964)
    at s.init (vendor.js:1:148730)
    at new s (vendor.js:1:132459)
    at u.fn.slick (vendor.js:1:172621)
    at i.initCarousel (calisphere.js:1:29525)
    at i.initialize (calisphere.js:1:30051)
    at l.View (vendor.js:1:586929)
    at new i (vendor.js:1:594889)
    at setupComponents (calisphere.js:1:560)
    at HTMLElement.<anonymous> (calisphere.js:1:38857)
```

**Comment by aturner** [comment] 2024-04-16 21:02
Checking an example object on -stage (https://calisphere-stage.cdlib.org/item/ark:/86086/n2ww7ks0/?order=0) -- it looks fine in MS Chrome and Edge now!

**Comment by barbarahui** [comment] 2024-04-16 21:06
Oh strange, the issue is resolved for me now too.

**Closed** 2024-04-19 18:00 UTC
Labels: bug, calisphere frontend
